name: LIME
options:
  bundleIdPrefix: com.lime
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1" # iPhone only
    INFOPLIST_FILE: LIME/Resources/Info.plist
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    CODE_SIGN_STYLE: Automatic
    ENABLE_PREVIEWS: YES

targets:
  LIME:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: LIME
        excludes:
          - "**/*.xcassets/*/Contents.json"
    resources:
      - path: LIME/Resources/Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.lime.app
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: 1
        DEVELOPMENT_TEAM: ""
    entitlements:
      path: LIME/LIME.entitlements

  LIMETests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: LIMETests
    dependencies:
      - target: LIME
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.lime.app.tests
