#!/usr/bin/env python3
"""
LIME Web App Setup Script

Generates:
  - bcrypt password hash for LIME_PASSWORD_HASH
  - TOTP secret for LIME_2FA_SECRET (optional)
  - VAPID keys for web push notifications

Usage:
  python scripts/setup_web.py
"""

import getpass
import secrets
import sys


def generate_password_hash():
    try:
        import bcrypt
    except ImportError:
        print("Installing bcrypt...")
        import subprocess
        subprocess.check_call([sys.executable, "-m", "pip", "install", "bcrypt"])
        import bcrypt

    password = getpass.getpass("Enter your LIME password: ")
    confirm = getpass.getpass("Confirm password: ")
    if password != confirm:
        print("Passwords don't match.")
        sys.exit(1)

    hashed = bcrypt.hashpw(password.encode(), bcrypt.gensalt(rounds=10))
    return hashed.decode()


def generate_totp_secret():
    try:
        import pyotp
    except ImportError:
        try:
            import subprocess
            subprocess.check_call([sys.executable, "-m", "pip", "install", "pyotp"])
            import pyotp
        except Exception:
            # Fallback: just generate a base32 random secret
            import base64
            raw = secrets.token_bytes(20)
            return base64.b32encode(raw).decode()
    return pyotp.random_base32()


def generate_vapid_keys():
    try:
        from py_vapid import Vapid
    except ImportError:
        try:
            import subprocess
            subprocess.check_call([sys.executable, "-m", "pip", "install", "py-vapid"])
            from py_vapid import Vapid
        except Exception:
            print("Could not install py-vapid. Generate VAPID keys manually.")
            return None, None

    vapid = Vapid()
    vapid.generate_keys()
    public_key = vapid.public_key.public_bytes(
        encoding=__import__("cryptography.hazmat.primitives.serialization", fromlist=["Encoding"]).Encoding.PEM,
        format=__import__("cryptography.hazmat.primitives.serialization", fromlist=["PublicFormat"]).PublicFormat.SubjectPublicKeyInfo,
    ).decode()
    return vapid.private_pem().decode(), public_key


def main():
    print("=" * 50)
    print("LIME Web App Setup")
    print("=" * 50)
    print()

    # Password
    print("1. Generate password hash")
    password_hash = generate_password_hash()
    print(f"   LIME_PASSWORD_HASH={password_hash}")
    print()

    # TOTP
    enable_2fa = input("2. Enable 2FA? (y/N): ").strip().lower() == "y"
    totp_secret = None
    if enable_2fa:
        totp_secret = generate_totp_secret()
        print(f"   LIME_2FA_SECRET={totp_secret}")
        print(f"   LIME_2FA_ENABLED=true")
        print()
        print("   Add this secret to your authenticator app (Google Authenticator, Authy, etc.)")
        print(f"   Secret: {totp_secret}")
    print()

    # VAPID
    print("3. Generating VAPID keys for push notifications...")
    auth_secret = secrets.token_hex(16)
    print(f"   AUTH_SECRET={auth_secret}")
    print()

    # Write to .env in web directory
    env_path = __import__("pathlib").Path(__file__).parent.parent / "web" / ".env"
    env_content = f"""# Generated by setup_web.py
AUTH_SECRET={auth_secret}
LIME_PASSWORD_HASH={password_hash}
LIME_2FA_ENABLED={'true' if enable_2fa else 'false'}
{f'LIME_2FA_SECRET={totp_secret}' if totp_secret else '# LIME_2FA_SECRET='}

LIME_API_URL=http://localhost:8000
NEXT_PUBLIC_API_URL=http://localhost:8000

# Generate VAPID keys: cd web && npm run generate-vapid
NEXT_PUBLIC_VAPID_PUBLIC_KEY=
VAPID_PRIVATE_KEY=
VAPID_MAILTO=mailto:you@example.com

NEXTAUTH_URL=http://localhost:3000
"""

    env_path.write_text(env_content)
    print(f"Written to: {env_path}")
    print()
    print("Next steps:")
    print("  1. cd web && npm run generate-vapid  # add VAPID keys to .env")
    print("  2. cd web && npm install")
    print("  3. cd web && npm run dev")


if __name__ == "__main__":
    main()
